### ISSUE TITLE
TypeError: new_counting_hash() takes at most 3 arguments (4 given) Again?

### ISSUE THREAD

**Issue by LeahRoberts** [mjsull/Contiguity#19]
Hi Mitch,

I pip installed the latest version of Contiguity but I'm still getting this error after running create CAG:
TypeError: new_counting_hash() takes at most 3 arguments (4 given).
I saw this has already been reported as a bug - has it been fixed?
Cheers,
Leah

**Comment by LeahRoberts** [comment]
Hi Mitch,

In regards to the above problem - I downloaded and installed Contiguity the old way (without pip) and it works now. Is there a way of fixing it so it can be pip installed?

**Comment by mjsull** [comment]
The versions on the webpage have fixed this issue
